version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: funder-reconciler:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4567:3000"
    networks:
      - fundernet
networks:
  fundernet:
